### ISSUE TITLE
hunger not going down

### ISSUE THREAD

**Issue by Celophy** [Mezy/UhcCore#60] opened 2020-11-28 20:24 UTC
the hunger is not going down! how can i fix it?

**Comment by Celophy** [comment] 2020-11-28 20:27
i am using the last version, without any other plugin, for an yt series

**Comment by steamsyyy** [comment] 2020-12-01 21:24
It's not supposed to go down in the first place.

**Comment by Celophy** [comment] 2020-12-02 18:38
i mean during the game

**Comment by steamsyyy** [comment] 2020-12-03 21:29
Yeah, that's what I mean. I've run games with friends and hunger has never been a problem. Searching for hunger in the config.yml returns no results, either, so enabling hunger isn't a feature yet.

**Comment by itoncek4** [comment] 2020-12-08 22:54
Duplicate of #45

**Closed** 2020-12-18 19:21 UTC
Labels: fixed
